### ISSUE TITLE
SEO: Dead links in Google search results and redirection to github.io

### ISSUE THREAD

**Issue by gautamkrishnar** [patternfly/patternfly.github.io#13]
**Describe the bug**
When I searched for "patternfly elements" on google, I fond several dead links in the google search results and clicking on any of those links redirected me to patternfly.github.io.

**To Reproduce**
1. Go to https://www.google.com/search?q=patternfly+elements
2. Click on any of the links

**Expected behavior**
1. Redirection shouldnt happen
2. Links should be working

**Screenshots**
Dead Links:
- https://www.patternfly.org/patternfly-elements/
- https://www.patternfly.org/patternfly-elements/develop/step-1b/ etc

![image](https://user-images.githubusercontent.com/8397274/74507079-6f6ab280-4f21-11ea-9adf-b472c0863fae.png)

Redirction issue:
Visit any of the dead links and it will redirect to github.io 404 page
![image](https://user-images.githubusercontent.com/8397274/74507540-b86f3680-4f22-11ea-8a9e-b45e46f94eb8.png)

**Additional context**
The page should be forcefully re-indexed. Also we need to add proper status codes for the 404 pages so  that search engines can detect dead links.

**Comment by gautamkrishnar** [comment]
@evwilkin can you please move this to https://github.com/patternfly/patternfly-org looks like it is the right repo!

**Comment by kylebuch8** [comment]
@gautamkrishnar I think our site gets blown away when the PatternFly team does a release for their site. I'll bug @evwilkin about it so we don't get caught with a bunch of 404s again.

**Comment by gautamkrishnar** [comment]
Thanks @kylebuch8. Closing this as per the dm discussion.
